create table category (
    id bigint generated by default as identity primary key,
    name varchar(50) not null unique,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null
);

create table users (
    id bigint generated by default as identity primary key,
    email varchar(100) not null unique,
    password varchar(255) not null,
    nickname varchar(30) not null unique,
    role varchar(20) not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null
);

create table document (
    id bigint generated by default as identity primary key,
    title varchar(150) not null,
    content text,
    summary varchar(255),
    event_year integer,
    content_json text,
    view_count bigint not null,
    fk_author_id bigint not null,
    fk_category_id bigint not null,
    fk_school_document_id bigint,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    constraint fk_document_author
        foreign key (fk_author_id) references users (id),
    constraint fk_document_category
        foreign key (fk_category_id) references category (id),
    constraint fk_document_school_document
        foreign key (fk_school_document_id) references document (id)
);

create table document_view_logs (
    id bigint generated by default as identity primary key,
    fk_document_id bigint not null,
    fk_user_id bigint,
    viewer_ip varchar(255),
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    constraint fk_document_view_logs_document
        foreign key (fk_document_id) references document (id),
    constraint fk_document_view_logs_user
        foreign key (fk_user_id) references users (id)
);

create table email_verifications (
    id bigint generated by default as identity primary key,
    email varchar(100) not null unique,
    code varchar(6) not null,
    verified boolean not null,
    expires_at timestamp(6) not null,
    verified_at timestamp(6),
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null
);

create table password_reset_tokens (
    id bigint generated by default as identity primary key,
    email varchar(100) not null unique,
    token varchar(100) not null,
    expires_at timestamp(6) not null,
    reset_token varchar(100),
    verified_at timestamp(6),
    reset_token_expires_at timestamp(6),
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null
);

create index idx_document_category_created_at
    on document (fk_category_id, created_at desc);

create index idx_document_school_created_at
    on document (fk_school_document_id, created_at desc);

create index idx_document_author
    on document (fk_author_id);

create index idx_document_view_logs_document_created_at
    on document_view_logs (fk_document_id, created_at desc);

create index idx_document_view_logs_user
    on document_view_logs (fk_user_id);
